#!/bin/bash
#export OMP_NUM_THREADS=$1
export OMP_NUM_THREADS=10
source ../../../lammps/env.sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib

#export CUDA_VISIBLE_DEVICES='' # to force CPU use
time ../../../lammps/src/lmp_serial < inputLMP_NVE
#../../../lammps/src/lmp_omp < input_NVE
#../../../lammps/src/lmp_mpi < input_NVE
